cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
spring:
  datasource:
    url: jdbc:postgresql://sample-rds-postgres.cl9lunwfwcm6.ap-northeast-1.rds.amazonaws.com:5432/sample_database
    username: postgresql
    password: postgresql
    driverClassName: org.postgresql.Driver